# Generated by Django 3.2 on 2025-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_auto_20250302_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
