# Generated by Django 4.1.13 on 2025-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_auto_20250302_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(default='誰か', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='どこか', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('mechanics', '力学'), ('electromagnetism', '電磁気学'), ('statistical_mechanics', '統計力学'), ('quantum_mechanics', '量子力学'), ('other_physics', 'その他の物理学'), ('mathematics', '数学'), ('other', 'その他')], max_length=100),
        ),
    ]
