# Generated by Django 4.1.13 on 2025-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_book_auther_book_publisher_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
